// TCAM Configuration File
// Generated by flow manager for logic synthesis
`define ARCH "LPM"	// TCAM   architecture
`define CDEP  8 	// CAM depth (k-lines)
`define PWID  1 	// pattern width(9bit)
`define PWRT  1 	// pipelined   writes?
`define REGM  0 	// register MLAB outs?
`define REGI  1 	// register    inputs?
`define REGO  1 	// register   outputs?
